[2024-12-02T09:33:23.033+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T09:33:23.058+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: IMDB_testing_DAG.transform manual__2024-12-02T09:33:11.961995+00:00 [queued]>
[2024-12-02T09:33:23.077+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: IMDB_testing_DAG.transform manual__2024-12-02T09:33:11.961995+00:00 [queued]>
[2024-12-02T09:33:23.078+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2024-12-02T09:33:23.122+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2024-12-02 09:33:11.961995+00:00
[2024-12-02T09:33:23.156+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'IMDB_testing_DAG', 'transform', 'manual__2024-12-02T09:33:11.961995+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpqbm6if7z']
[2024-12-02T09:33:23.160+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=51818) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T09:33:23.163+0000] {standard_task_runner.py:105} INFO - Job 66: Subtask transform
[2024-12-02T09:33:23.163+0000] {standard_task_runner.py:72} INFO - Started process 51881 to run task
[2024-12-02T09:33:23.309+0000] {task_command.py:467} INFO - Running <TaskInstance: IMDB_testing_DAG.transform manual__2024-12-02T09:33:11.961995+00:00 [running]> on host a34e3ee3c8c3
[2024-12-02T09:33:23.493+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='IMDB_testing_DAG' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T09:33:11.961995+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T09:33:11.961995+00:00'
[2024-12-02T09:33:23.496+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-02T09:33:23.498+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-02T09:33:23.499+0000] {logging_mixin.py:190} INFO - Current task name:transform state:running start_date:2024-12-02 09:33:23.059360+00:00
[2024-12-02T09:33:23.500+0000] {logging_mixin.py:190} INFO - Dag name:IMDB_testing_DAG and current dag run status:running
[2024-12-02T09:33:23.500+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T09:33:23.874+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/src/transform/transform.py", line 111, in transform
    dim_genre = create_dimension_table(null_handled_df,['genre'],'genre_id',generate_hash)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/src/transform/transform.py", line 76, in create_dimension_table
    dim_table = df[columns].dropduplicates()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'dropduplicates'. Did you mean: 'drop_duplicates'?
[2024-12-02T09:33:23.927+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-02T09:33:23.928+0000] {logging_mixin.py:190} INFO - Task start:2024-12-02 09:33:23.059360+00:00 end:2024-12-02 09:33:23.925871+00:00 duration:0.866511
[2024-12-02T09:33:23.929+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform> dag:<DAG: IMDB_testing_DAG> dagrun:<DagRun IMDB_testing_DAG @ 2024-12-02 09:33:11.961995+00:00: manual__2024-12-02T09:33:11.961995+00:00, state:running, queued_at: 2024-12-02 09:33:12.247679+00:00. externally triggered: True>
[2024-12-02T09:33:23.929+0000] {logging_mixin.py:190} INFO - Failure caused by 'DataFrame' object has no attribute 'dropduplicates'
[2024-12-02T09:33:23.930+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=IMDB_testing_DAG, task_id=transform, run_id=manual__2024-12-02T09:33:11.961995+00:00, execution_date=20241202T093311, start_date=20241202T093323, end_date=20241202T093323
[2024-12-02T09:33:23.959+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-02T09:33:23.960+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 66 for task transform ('DataFrame' object has no attribute 'dropduplicates'; 51881)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/src/transform/transform.py", line 111, in transform
    dim_genre = create_dimension_table(null_handled_df,['genre'],'genre_id',generate_hash)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/app/src/transform/transform.py", line 76, in create_dimension_table
    dim_table = df[columns].dropduplicates()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'dropduplicates'. Did you mean: 'drop_duplicates'?
[2024-12-02T09:33:24.048+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-02T09:33:24.079+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-02T09:33:24.086+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
